Splash page
pennlabs/OHQ pull request #6
Opened 2016-11-19 21:00 UTC by sknop8

Implemented Tiffany's splash page mockups. *Not fully mobile responsive yet*

2016-11-19 21:08 UTC, adelq commented on frontend/src/components/SplashPage.react.js
> +            src={'https://cdn.zeplin.io/5827a5a8096f25bc1a22dab7/assets/91F41CD0-1042-429B-A05B-FD0AE7C7B3A2.png'}
These look pretty blurry, guessing they were compressed. Can you have Tiffany render the vector into the size that you want and add that to the repository and serve it directly?

2016-11-19 22:02 UTC, armic requested changes

2016-11-19 22:02 UTC, ajmichaels commented on frontend/src/components/Class.react.js
> +import React, { Component } from 'react'
Looks like this is a demo/learning file right?  Best not to include this.

2016-11-19 22:02 UTC, ajmichaels commented on frontend/src/components/app.react.js
> +// import Header from './Header.react'
Don't need these two lines

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/class.scss
> +:local .class {
This seems to be part of the demo file; I don't think we need it.

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    @media screen and (max-width: 500px) {
Please keep `@media` tags in their own section

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    -webkit-box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.1);
We have a library called autoprefixer in our app that automatically adds prefixes for us; all you need is to say box-shadow.  Though in this case, prefixing box-shadow is not necessary: see http://caniuse.com/#feat=css-boxshadow

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    transition: background-color 100ms;
Like above, don't need to manually add the prefixes

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    display:inherit;
Usually inheriting is best used when we're dependent upon the parent element somehow.  In this case, all you want is display flex, which presumably is active regardless of how the parent element is laid out, so it's better to be explicit about it and just write `display: flex`

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    flex-direction:inherit;
See above, better to be explicit

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    img{
Please don't set style tags to dom elements like this, setting to classes is much cleaner.  It's not really an issue since we're using unique selectors, but it's better practice.

2016-11-19 22:02 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +    display:inherit;
See below; just say `display: flex` here

2016-12-01 23:56 UTC, sknop8 commented on frontend/src/components/SplashPage.react.js
> +            src={'https://cdn.zeplin.io/5827a5a8096f25bc1a22dab7/assets/91F41CD0-1042-429B-A05B-FD0AE7C7B3A2.png'}
@ajmichaels was working on adding local images, so when we figure that out we can use larger image files directly.

2016-12-02 22:32 UTC, ajmichaels commented on frontend/style/splashpage.scss
> +  font-family: Roboto;
Not necessary - we already have Roboto as the default :)

2016-12-02 22:34 UTC, ajmichaels commented
@sknop8 looks good.  Is this ready to be merged?

2016-12-02 22:34 UTC, armic approved these changes

2016-12-03 18:52 UTC, merged